name: Every Five Minutes Test Here

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  # We are using a Linux runner here for Docker compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with Allure Reporter
        run: npx playwright test Input.test --headed --reporter=allure-playwright

      - name: Install Allure Commandline via npm
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
        working-directory: ${{ github.workspace }}

      - name: Run Allure Server in Docker (Optional)
        run: |
          docker run -d -p 8080:8080 -v $(pwd)/allure-report:/allure-report allure/allure
        continue-on-error: true  # Continue running even if this fails (optional)

      - name: Upload Allure Report as Artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: ${{ !cancelled() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report  # Allure report directory
          publish_branch: gh-pages  # GitHub Pages branch
